### ISSUE TITLE
Unable to download audio (mp3/wma) file on Android 8.0

### ISSUE THREAD

**Issue by lessneek** [element-hq/element-android#1895]
Unable to download audio (mp3/wma) file on Android 8.0. When I click on the download button alongside with file in the uploads list of a chat/room. It can open default audio player, but there is no downloaded file in any directory.

 - Device: Samsung S7
 - OS: Android 8.0

 - App version and store 1.0.4 - F-Droid
 - Homeserver: matrix.org

**Comment by BillCarsonFr** [comment]
You don't get this after the download?

**Comment by lessneek** [comment]
Yes, I don't have any notification.

**Comment by BillCarsonFr** [comment]
Can you try a download and then submit a rageshake (top right 3 dots menu on home screen > report bug) add the reference to this issue (#1895)

**Comment by 532910** [comment]
Check #1922
