### ISSUE TITLE
Element Android still uses "Recovery Passphrase" rather than "Security Phrase"

### ISSUE THREAD

**Issue by aaronraimist** [element-hq/element-android#2726]
**Describe the bug**
Element Android uses the old name for "Security Phrase" and "Security Key"

**To Reproduce**
1. Sign in to Element Android

**Expected behavior**
I should be asked to verify with another device or use my Security Phrase or Key

**Screenshots**
![Screenshot_20210126-160752](https://user-images.githubusercontent.com/5855073/105912442-1a6c6300-5ff1-11eb-8040-e20e58dec1a6.png)
![Screenshot_20210126-160828](https://user-images.githubusercontent.com/5855073/105912454-1d675380-5ff1-11eb-8bf5-0a17ce6f4d94.png)

**Additional context**
 - App version and store: 1.0.14 Google Play

**Comment by richvdh** [comment]
Seems we're no longer planning to switch to "security phrase/key": https://github.com/element-hq/element-meta/issues/2394#issuecomment-2072179275
