### ISSUE TITLE
Join/Register/Sign-in/Create Account choice of wording

### ISSUE THREAD

**Issue by ManDay** [element-hq/element-android#3172]
Whereever it is meaningful, a clearer wording concerning authentication processes should be used. Particularly, "*Sign-in*" and "*Register*" should be avoided as most people do not recognize their intended meaning. Instead "*Sign-in using an existing account*" and "*Create a new account*" should be used.

NB: Especially confusing in, say, German with "*Registrieren*" and "*Anmelden*"

**Comment by bmarty** [comment]
This has been improved in #3188 , but the new login flow is not enabled for now
