### ISSUE TITLE
[SDK] SDK V2, no API for login with login type parameter - Cannot login. 

### ISSUE THREAD

**Issue by isabeD** [element-hq/element-android#4266]
### Description

Our Matrix environment / synapse supports "proprietary" login flow. 
Requesting from app the list of loginFlow supported types returns a list like this : 
m.login.password
com.xx.login.istra
... 

Using SDK V2, no API permit to add the login type "com.xx.login.istra" as parameter. 
That prevent our android app to login using regular API authenticationService / Wizard which always returns an error code "FORBIDDEN". 
As workaround, app perform login out of Matrix SDK - app send an HTTP request + appropriate json  adding type = com.xx.login.istra. That's not good, we do not mesure very well the side effects of that.

**Comment by isabeD** [comment]
Hi, Thanks for your quick answer. 

According your proposal app should call  : 
loginCustomData(myjsonDict) 

with  that kind of jsonDict  key / values : 
type : com.xx.login.istra
initial_device_display_name : "mydevice"
password: "mypwd"
user: "@xx"

SDK execute request https://homeserver/_matrix/client/r0/login + payload issued from jsonDict 
... Matrix do its SDK stuffs. 
Then Matrix SDK returns a session -if login ok-  If I'm correct that fit our needs!

**Comment by bmarty** [comment]
One confirmation please :

The request ` https://homeserver/_matrix/client/r0/login + payload issued from jsonDict` will return regular [Credentials](https://github.com/matrix-org/matrix-android-sdk2/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/data/Credentials.kt#L30)?
