### ISSUE TITLE
EditText view broken on title of room

### ISSUE THREAD

**Issue by chagai95** [element-hq/element-android#4276]
### Steps to reproduce

1. creating a room and trying to type a title

https://user-images.githubusercontent.com/31655082/138089067-1a268069-d440-4f7a-be0c-0902fe32f42a.mp4

### Intended result and actual result

It should work

### Your phone model

Galaxy A51

### Operating system version

One UI 3.1, Android 11

### Application version and app store

1.3.3 [40103032] (G-b3874)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ariskotsomitopoulos** [comment]
Can you please confirm that the issue is fixed after my PR?
