### ISSUE TITLE
Video call with camera off shows black screen

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-android#4301]
### Steps to reproduce

1. Start a video call with other person's camera off

#### What did you expect?
User's avatar is shown if their camera is off or if there is a connection issue.

#### What happened instead?
There's no indication if the connection is slow or if the user has camera off or if something is broken

### Application version and app store

Element 1.3.4

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Duplicate of https://github.com/vector-im/element-android/issues/3734 and https://github.com/vector-im/element-android/issues/3790
