### ISSUE TITLE
Rolling "Waiting for that message" bug (Last message always in UTD)

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-android#5905]
Rageshake description:

> I am getting "Waiting for this message, this may take a while" constantly. It's always the last message I've received. When I receive a new message from the same contact and restart the application, the previously unavailable message suddenly appears.

https://github.com/matrix-org/element-android-rageshakes/issues/36546

**Comment by BillCarsonFr** [comment]
Related to https://github.com/vector-im/element-android/issues/1721#issuecomment-1115753812

**Comment by ggajews** [comment]
It happens to me only when I verify my session using another session.
Always for last message in the room (no matter if 1:1 or regular room)
If I'm using the recovery key it is working fine.

**Comment by returntrip** [comment]
This happens regularly with one specific contact . It used to happen with a different contact but then I had to clear data for Element and the issue shifted to a different user.

**Comment by wioxjk** [comment]
I am that specific contact that @returntrip talks about.
The issues seems to appear after a while for messages that I am sending from my android phone - but other clients works fine.

**Comment by jtrees** [comment]
This is marked in https://github.com/vector-im/element-meta/issues/245 as "Will be fixed with Element R". Since Element Android is now uses the Crypto Rust SDK, does that mean this issue is resolved?

**Comment by BillCarsonFr** [comment]
Resolved with rust sdk as all this part of the code has been replaced, and it was specific to android legacy crypto
