### ISSUE TITLE
when you reply to someone and then edit it, it double quotes for desktop and web/desktop makes 0 (zero) quotes for phone

### ISSUE THREAD

**Issue by G2G2G2G** [element-hq/element-android#5969]
### Steps to reproduce

1. reply to someone using any element client
2a. editing with the desktop will break the quote on element-android
2b. editing with element-android will make it double quote on element-desktop

(2a / 2b are either/or type of thing)

#### What did you expect?
1 quote, quoting the post you are replying to
#### What happened instead?
Depending on what you use to edit:
- the phones either show 1 quote of the same reply (in this case the desktop then shows 2 quotes)
- or phones show no quotes at all and desktop shows one

element web/desktop doesn't seem to be the issue since it can always see the quotes.. the phone seems to be adding a "phone only" quote which element-desktop then shows that AND the regular quote. Where-as if it is the desktop that edits, the phone cannot see any quote

let me know if I wasn't thorough enough.. it is easy to do this bug

### Your phone model

tested on s5, s8, s9, s20, fold

### Operating system version

several

### Application version and app store

f-droid and google play versions

### Homeserver

synapse newest

### Will you send logs?

No

**Comment by KeenMaron** [comment]
Any updates for this bug?

**Comment by giomfo** [comment]
reproduced with Element-Android v1.6.8
