### ISSUE TITLE
`Verify this login` toast pops up when there is no way to do it (no other devices or 4S)

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-android#6466]
If you login on a new device and you don't have other active logins nor 4S, android will prompt you to verify but there is actually no way to do it.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/9841565/177298844-a2761972-3459-4ef2-ba64-8b18f1f372fc.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/9841565/177298854-0df5b179-57ed-4093-8562-8bfb2b1d172e.png">

For reference web is showing this:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/9841565/177298916-1e9eb6b2-954c-4bf7-8f4a-8adf90934732.png">

## Short term fix:

Align with web. Show a popup stating that you have lost access to e2ee history and propose to reset cross signing and properly setup 4S.

## Long term fix.

This will need a bit more thinking.
But basically, why don't we just silently reset cross-signing keys?
Do we really need to do a full bootsrap (xsigning, backup + 4S?)?
Maybe this could be just an opportunity to explain the benefits of backup and 4S? And to explain why e2ee history is not accessible?

**Comment by dkasak** [comment]
> But basically, why don't we just silently reset cross-signing keys?

I think it's always a bit iffy if an untrusted party (in this case, the HS) is able to make the client modify or drop local crypto-related state. I don't have a ready-made attack scenario, but I feel it's not a property we want to lose. Resets should always be user-initiated, IMO.

> Maybe this could be just an opportunity to explain the benefits of backup and 4S? And to explain why e2ee history is not accessible?

Probably shouldn't spell it all out in a huge block of text, though. Maybe a bit of "Why is this required for accessing encrypted message history?" green text at the bottom, which summons a new screen or a modal which explains it in more detail.
