### ISSUE TITLE
Login via QR code: The device is not authenticated and the message cannot be decrypted.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-android#7554]
May be related to #7511.

### Steps to reproduce

1. Download and install a development build from Buildkite to the device;
2. Launch it, and enable the "Login via QR Code" related function;
3. Get the QR code from Element Web or Element Desktop;
4. Scan the QR code on your device to log in.

#### What did you expect?
After logging in via QR code, device verification should be done and the key downloaded to the device to decrypt the message.

#### What happened instead?
After logging in via QR code, Element Web or Element Desktop shows that the device is verified, but the device shows that it is not verified. At this point, the encrypted message cannot be decrypted and requires manual verification again.
![{E4BE8E2F-8B6D-D79A-BEBE-679AE8FEADF9}](https://user-images.githubusercontent.com/48104960/200752876-134996e1-b2c4-4c72-a532-5fae9ac3e9e0.png)

**Given that "login via QR code" is an experimental feature, I'm not sure if it's a bug or intentional. I think the QR code is usually sent from a trusted device, so it should be equivalent to manually authenticating a session.**

### Your phone model

HMD Global TA-1054

### Operating system version

Android 8.1

### Application version and app store

Element Android 1.5.8-dev (F-b12481)

### Homeserver

Synapse 1.71.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by magrimuc** [comment]
"Download and install a development build from Buildkite to the device;"
How is that done?
Is there a buildkite url e.g.?

**Comment by magrimuc** [comment]
"enable the "Login via QR Code" related function"
How is that done?
(Thanks in advance)

**Comment by YamatoRyou** [comment]
> "enable the "Login via QR Code" related function" How is that done? (Thanks in advance)

- Buildkite has been deprecated and replaced by GitHub Actions: https://github.com/vector-im/element-android/actions/workflows/build.yml?query=branch%3Adevelop, download recent build artifacts from there ( Some builds may be unstable).
- "Login via QR Code" is currently only available in the debug version. After launching the app, click the "gear" and then click "Features" to find it.

**Comment by warioishere** [comment]
sorry guys, does anyone know why it shows me a `processing failed`

when i call https://myserver/_synapse/client/org.matrix.msc3886/rendezvous

running latest matrix synapse, follwed the steps on 
https://github.com/matrix-org/synapse/issues/15918#issuecomment-1631439515

installed matrix-http-rendezvous-synapse

synapse starts without errors with this setup

**Comment by YamatoRyou** [comment]
> sorry guys, does anyone know why it shows me a `processing failed`
> 
> when i call https://myserver/_synapse/client/org.matrix.msc3886/rendezvous
> 
> running latest matrix synapse, follwed the steps on [matrix-org/synapse#15918 (comment)](https://github.com/matrix-org/synapse/issues/15918#issuecomment-1631439515)
> 
> installed matrix-http-rendezvous-synapse
> 
> synapse starts without errors with this setup

https://github.com/element-hq/synapse/issues/18027#issuecomment-2539011601
