### ISSUE TITLE
"Are you a human?" captcha page stays blank

### ISSUE THREAD

**Issue by PassionateG1t** [element-hq/element-android#7580]
The captcha verification never loads so I'm stuck in account registration.

![Screenshot_63g3f4yeueh](https://user-images.githubusercontent.com/107609269/201680753-355da6ce-2431-47a3-8e0d-9d3047fffbcb.jpg)

**Comment by jmartinesp** [comment]
Hi, could you send some logs so we can understand what's causing this issue for you? 

Also, are you using some ad-blocker such as pi-hole, adaway, etc.? The captcha page needs to load some info from Google's reCAPTCHA, so that might be what's causing the issue.
