### ISSUE TITLE
Replies show up as empty space (mautrix-discord bridge)

### ISSUE THREAD

**Issue by rajil** [element-hq/element-android#8460]
### Steps to reproduce

I am using a mautrix-discord bridge. If anybody replies to my message it shows up as a white space in Element Android. However, it renders fine in Element Desktop. If you long press on the 'empty space' and share it, Element correct shows the message in the preview popup. So it seems that the text is present but its color is matching the background color and thus it shows up as white space. 
The ghost message is like this,

```
{
  "type": "m.room.message",
  "room_id": "!redacted:redacted.com",
  "sender": "@discord_164751726268121099:redacted.com",
  "content": {
    "body": "Some text",
    "com.beeper.linkpreviews": [],
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$MVPSWYZFm2a4WCnSJTXLdoOc-xQkeSEeuNXiYfMovZY"
      }
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 3681727111576,
  "unsigned": {
    "age": 73538102
  },
  "event_id": "$myGciNpYTaQNWMjX-Gn5fgpzGNMXGw6cSAWcwhT3gWk",
  "user_id": "@discord_164751726268121099:redacted.com",
  "age": 73538102
}
```

#### What did you expect?
Message to be readable in Element Android
#### What happened instead?
Message shows up as empty space.

### Application version and app store

Element Android 1.6.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ajay-actuary** [comment]
I can reproduce this. Msgs appear as blank in the mautrix discord bridge.

**Comment by rom4nik** [comment]
Similar issue (no fallback in reply body): https://github.com/vector-im/element-android/issues/8432#issuecomment-1552144286
