### ISSUE TITLE
With rich text format enabled word suggestions are not working properly in Gboard

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-android#8712]
### Steps to reproduce

In an Android device with version >= 13:

1. Enable rich text editor in labs.
2. Start writing a message using word suggestions.

At some point, you'll probably notice what you type and what's displayed in the keyboard doesn't match.

#### What did you expect?

The text written should match the input.

#### What happened instead?

The RTE doesn't update its contents properly.

----

This should be fixed by https://github.com/matrix-org/matrix-rich-text-editor/pull/902 in the RTE library, and updating to `v2.22.0` should automatically fix it in EA.

### Your phone model

One Plus 11

### Operating system version

13

### Application version and app store

1.6.8

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Fixed in #8711
