### ISSUE TITLE
Keyboard suggestions are ignored 

### ISSUE THREAD

**Issue by ldicarlo** [element-hq/element-android#8717]
When changing a word using the keyboard suggestions, the original word is sent instead of the suggestion

I'll add a screen recording soon.

I use the last element app from play store and Gboard.

**Comment by ldicarlo** [comment]
https://github.com/element-hq/element-android/assets/15803534/66db7476-0055-4154-8561-0fa87176f2fc

**Comment by ithinuel** [comment]
I confirm I experience the same behaviour.

**Comment by wlallemand** [comment]
Same problem here, I think the problem appeared with the latest update of the element app. This is difficult to type correctly this way. I also use Gboard and the element app from the play store.

**Comment by ithinuel** [comment]
It's worth nothing this also happen with element-x-android.

**Comment by wlallemand** [comment]
It looks like I don't have the problem anymore with the v1.6.10 from the f-droid store.

**Comment by ldicarlo** [comment]
Same here from play store.
Seems to be resolved.
