### ISSUE TITLE
Release 1.6.10 - threads don't load and unable to reply to messages

### ISSUE THREAD

**Issue by scottwallacesh** [element-hq/element-android#8732]
### Steps to reproduce

With release 1.6.10,
* I am unable to load threads, it just "spins" forever.
* I cannot reply to messages. The option simply isn't available.

#### What did you expect?
Threads would load and I am able to reply to messages.

#### What happened instead?
Threads didn't load and the option to reply to messages wasn't available.

### Your phone model

Google Pixel 7a

### Operating system version

GrapheneOS 2024010400

### Application version and app store

Element Android v1.6.10

### Homeserver

Synapse v1.98.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Hello @scottwallacesh , thanks for reporting.
I have no issue with thread and reply on the release candidate. Sometimes loading the thread content can take a few seconds. Can you double check please?

**Comment by bmarty** [comment]
I still do not repro the issue. Can you post a video showing the issue @scottwallacesh ?

**Comment by scottwallacesh** [comment]
I just re-upgraded to v1.6.10 again and everything's working as it should be now.

Very strange - I wonder what happened the previous time I upgraded?

**Comment by scottwallacesh** [comment]
Something's still not right. Some thread overview pages load and others don't.
 (just spinning).

I've reverted to v1.6.8 for now and everything's stable.

I won't reopen this issue since it only appears to be me with this problem.
