### ISSUE TITLE
Message keys not migrated from legacy to Rust store are not backed up after backup reset

### ISSUE THREAD

**Issue by yostyle** [element-hq/element-android#8814]
#### case 1 (with key backup)

1. Install Element 1.5.32 or older (any other version without crypto rust)
2. Send some events in rooms to have a significant history.
3. Upgrade to Element 1.6.8 (higher version could crash, it's another problem to report...)
4. Don't open the rooms
5. **Reset secure backup**
7. Create a new session on any Matrix client like Element X (or Element Web)
8. On the new session restore from backup
9. Open a room

#### case 2 (without key backup)

1. Install Element 1.5.32 or older (any other version without crypto rust)
2. Send some events in rooms to have a significant history.
3. Upgrade to Element 1.6.8 (higher version could crash, it's another problem to report...)
4. Create a new session on any Matrix client like Element X (or Element Web)
5. Open a room

#### What did you expect?
All events should be decryptable.

#### case 1 (with key backup)
All events are undecryptable because message keys (Megolm sessions) are not backed up.

Only message keys migrated to the Rust crypto store are backed up to the server-side key backup. **Message keys that are not present in the Rust crypto store are missing in the key backup.**

#### case 2 (without key backup)
All events are undecryptable because message keys (Megolm sessions) are not sent to the Element X session by key request feature.

Only message keys migrated to the Rust crypto store could be exchanged between sessions.

### Your phone model

Pixel 8 Pro

### Operating system version

Android 14

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by yostyle** [comment]
@giomfo do you have a plan about this issue ?

It could impact some users on Element X, Element 1.6.8 and higher.

**Comment by toshanmugaraj** [comment]
Here is another issue in open related to the crash happening on migration in Android:

https://github.com/element-hq/element-android/issues/8799

**Comment by toshanmugaraj** [comment]
> @yostyle internal discussions are still in progress about this key migration issue

@giomfo is there any conclusion on the issue reached.

**Comment by yostyle** [comment]
@giomfo we can reproduce the same issue without key backup configured on the user account.

**Comment by BillCarsonFr** [comment]
Hello, while migrating all the session would fix this scenario, it will not complitely fix the problem. For example in this migration case, the keys are already offloaded in the backup.
The problem is that the reset backup flow that can cause key loss, and we could take action to reduce the chance of key loss by doing also something like that https://github.com/element-hq/element-meta/issues/2446

**Comment by richvdh** [comment]
> Hello, while migrating all the session would fix this scenario, it will not completely fix the problem. For example in this migration case, the keys are already offloaded in the backup.

To be clear, there are two separate problems here.

1. If you had set up key backup *before* migrating to rust, then all the keys that were previously in the Realm DB will also be in the key backup. This is fine, unless the user resets their key backup, which can cause keys to be lost. This is the same problem as https://github.com/element-hq/element-meta/issues/2446.

   It is worth noting that resetting key backup should be an unusual operation. Indeed, as I understand it, "Reset Secure Backup" in Element Android does not actually reset the key backup -- it in fact resets secret storage (which is used to store the backup key), but if backup was working on the client before the reset, the same key backup should continue to work afterwards (see [`PASSPHRASE_RESET`](https://github.com/element-hq/element-android/blob/b0158f1a93499b736a92285d8a7359a51a2d8921/vector/src/main/java/im/vector/app/features/crypto/recover/SetupMode.kt#L36)). It is therefore expected that very few users will hit this case.

2. If you had *not* set up key backup before migration, then there exist keys which are only in the Realm DB. Then, when you come to configure key backup later, those keys are not backed up. I have opened a separate issue to track this: https://github.com/element-hq/element-android/issues/8858.

   In addition, key requests/sharing are not supported by modern clients: the only "key sharing" mechanism now supported is via key backup.

**Comment by giomfo** [comment]
@yostyle According to the point 1. summarised by @richvdh above, the Reset secure backup that you did in your case 1 (step 5) should not impact the backed up keys server side.

Do you know when the backup is set up in your case 1? Indeed if you set up the backup for your test after "Upgrade to Element 1.6.8" (step3), then you are mainly impacted by point2. This is the only reason, I can see, to explain the missing keys in the backup after the reset secure backup

**Comment by yostyle** [comment]
@giomfo the secure storage has been recreated and not only reset. Our problem is the creation of a new secure storage. In this case all keys in Realm DB are not backed up. This is the second point of @richvdh comment.
