### ISSUE TITLE
Log devices sent to with /sendToDevice

### ISSUE THREAD

**Issue by kegsay** [element-hq/element-android#8843]
As part of debugging unable to decrypt issues, I need to look at Element Android logs. The logs however lack the detail found in Element X Android, specifically:
 - it does not log which devices it is sending a room key to in `/sendToDevice`.

Please can it do this so I can confirm that the sender is sending room keys to the right devices.

**Comment by andybalaam** [comment]
Might just need configuration of logging in the sdk modules.

**Comment by BillCarsonFr** [comment]
I think it does log that:
https://github.com/element-hq/element-android/blob/b0158f1a93499b736a92285d8a7359a51a2d8921/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/crypto/tasks/SendToDeviceTask.kt#L84

**Comment by BillCarsonFr** [comment]
Maybe we would want to re-consider https://github.com/matrix-org/matrix-rust-sdk/pull/3274 ?
Looks like it's common that we don't have enough log history?
