### ISSUE TITLE
Bridged "Answers" are not visible only on Android Version

### ISSUE THREAD

**Issue by smooth-baking-powder** [element-hq/element-android#8866]
### Steps to reproduce

1. Bridge Signal
2. Chat with User
3. The User answer on your Text

#### What did you expect?
I can see the Message

#### What happened instead?
I cant see the Message

Android:
![3zabSRk2M9](https://github.com/user-attachments/assets/e352ae0c-2d94-4d55-bb74-53beec23f39a)

Desktop:
![TmNpUNLiBu](https://github.com/user-attachments/assets/611975d8-f711-41f9-9b95-60a04bc4ed09)

### Your phone model

Pixel 7 Pro

### Operating system version

Android 14

### Application version and app store

1.6.18 [40106182] (G-02631830)

### Homeserver

Matrix Synapse 1.110.0

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by tchernobog** [comment]
Can reproduce with mautrix-signal replies

**Comment by corincorvus** [comment]
Can reproduce the Problem with both Discord Bridges. This is a Discord Conversation 1:1
![2024-07-26_12-26](https://github.com/user-attachments/assets/37a6f262-6e43-461e-9d67-fec5badd781d)
![2024-07-26_12-27](https://github.com/user-attachments/assets/f1cd92cb-dda3-4777-b570-2f8f148a6918)

**Comment by SapuSeven** [comment]
Seems to be the same issue as #8432 and #8162.

A potential fix was provided recently: https://github.com/element-hq/element-android/issues/8162#issuecomment-2249178511

**Comment by corincorvus** [comment]
> Seems to be the same issue as #8432 and #8162.
> 
> A potential fix was provided recently: [#8162 (comment)](https://github.com/element-hq/element-android/issues/8162#issuecomment-2249178511)

Yes, looks similar. I cant publish a new patch for the client :/

**Comment by MrXANA91** [comment]
I also get this issue with a mautrix-meta bridge. No issue on Web client but all the answers on Android are blank. I have to to do a long-press to read the message, hoping it's not too long in the preview.
