### ISSUE TITLE
App looses microphone access when not active on v 1.6.20

### ISSUE THREAD

**Issue by dmgartung** [element-hq/element-android#8881]
### Steps to reproduce

1. When on a voice call, click Home button or switch to other app

#### What did you expect?
Continue conversation easily without interruptions while switching to other apps or lock the phone.
#### What happened instead?
Voice call party do not hear you because app looses access to microphone. It is noticeable on Samsung (S24) as green dot in the upper right corner (indicating microphone access) dissappears.

Works perfectly fine on 1.6.18

### Your phone model

Samsung S24 Ultra

### Operating system version

Android 14

### Application version and app store

Element version 1.6.20 I. G Play store

### Homeserver

matrix

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by romawkafor** [comment]
I faced the same problem on about 10 new Samsung devices running Android 14

**Comment by adi-vizgan-unplugged** [comment]
I have the same issue, and I have further information:
When I compile Element's code with targetSdk set to 33, the issue does not happen. Probably Google changed something between targetSdk 33 and targetSdk 34, IDK what.

**Comment by throwException** [comment]
I can confirm this on a Pixel 6a using GrapheneOS.

This should be fixed urgently as it keeps me from doing hands-off calls.

**Comment by bro2020** [comment]
I confirm this.
Element-web:v1.11.75
Synapse:v1.114.0
Android app: 1.6.20 [40106202](G-fca16b67) (With Google Play)

Reproduced on:
Samsung Galaxy S20 (Android 14)
Pixel 7 Pro (Android 14)

Does not reproduce on:
Xiaomi Mi10T (Android 12)

**Comment by aprettij** [comment]
The same problem occurs using Moto G84 and Samsung S21 (Android 14)

**Comment by dmgartung** [comment]
@bmarty Hello. Is there any chance that this bug can be patched? Those who that don't know how to downgrade or use GitHub are basically cant use this app calls. I see there are updates for Element X but not for this client.

**Comment by profitrollgame** [comment]
I can confirm this is still the case on 1.6.22 [40106222] (G-9a4602bf).

Tested on the OnePlus 7T Pro (A14).

Calls are nearly unusable. Including the fix from PR in the next release would be highly appreciated.

**Comment by kirkawolff** [comment]
This has been an annoyance for quite some time. Whenever browsing to another app or the screensaver kicks in, my microphone is muted. On Element 1.6.22, GrapheneOS build 2024092900 android 14, pixel 6pro.

**Comment by dmgartung** [comment]
So I tested **new released version 1.6.22** and the bug **still present** in that version.

**Comment by kirkawolff** [comment]
The changes from this ticket were merged a day or two after that release.

**Comment by kirkawolff** [comment]
When do we get this bug fix in a release?

**Comment by j4mt** [comment]
I also face this issue on Samsung s22 mentioned above when switching Apps.

**Comment by jsiit** [comment]
I can also confirm this problem on Note 20 Ultra 5G (Android 13, Element 1.6.22 [40106222] (G-9a4602bf))
Are there any updates on whether this problem is fixable?

I tested Element X a time ago and found it incomplete and not very usable. Can anybody give a status on how that improved (hopefully)?

**Comment by mdhanif-simformsolutions** [comment]
Starting Android 14 you can't record audio if the app is in background unless you use a foreground service with at least microphone type.

**Comment by kirkawolff** [comment]
The latest release fixes this. Thank you!

**Comment by furyritchie** [comment]
Same issue.

1.6.22 
Samsung Galaxy 22+
Android 14

**Comment by profitrollgame** [comment]
The issue is not observed anymore on Android 14 with Element 1.6.24. Thanks for the fix!

**Comment by bro2020** [comment]
This issue should be closed

**Comment by dmgartung** [comment]
Resolved in 1.6.24 even though update is not on Google Play yet.
