### ISSUE TITLE
1.6.20 for F-Droid

### ISSUE THREAD

**Issue by voidanix** [element-hq/element-android#8888]
Element 1.6.20 has been released on July 25th. Is it possible to get in touch with the F-Droid team and update them on the status?

Due to the lack of authenticated media support in 1.6.18, the current experience is somewhat dreadful with homeservers enforcing it.

**Comment by cbs228** [comment]
1.6.20 is still not available on f-droid. Per build logs for that version code, the build appears to have failed: <https://f-droid.org/repo/im.vector.app_40106201.log.gz>

I'm not a gradle or Java expert, but this line is probably key:

```log
ERROR: R8: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by licaon-kter** [comment]
Only the armv7 failed, the others are awaiting publishing in about 2 hours: https://monitor.f-droid.org/builds/running

**Comment by voidanix** [comment]
The update is now on the official repo, closing. For armv7 it would be wise to open another issue over at F-Droid.

**Comment by licaon-kter** [comment]
It would be retried
