### ISSUE TITLE
Can't login into my server from newly installed Element

### ISSUE THREAD

**Issue by Manifoldme** [element-hq/element-android#8897]
### Steps to reproduce

Issue: I enter my server address and the app returns ".well-known not available".
Element 1.6.18
Samsung S21 Ultra, 
Android 14,
One UI 6.1, 
Security Patch August.

I've been self-hosting Synapse for about six years without federation/delegation, so .well-known is not present in my installation.
First I had a problem with the microphone on 1.6.20, where after a screen went off, my microphone also went off.
So I tried Schieldi, but it never worked for me in the past and the notification issue is still there, so I installed the older version of Element from F-Droid 1.6.18, but suddenly
I experience the same problem I had with ElementX which works over proxy, and that's why I don't use it.
Update. 
Synapse 1.114.0+Bookworm1
has integrated sliding sync, that's might be the culprit.

#### What happened instead?
.well-known not available

### Your phone model

Samsung S21 Ultra

### Operating system version

Android 14

### Application version and app store

1.6.18

### Homeserver

Synapse 1.114.0+Bookworm1

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by Alex11381** [comment]
I have same problem. How you fix it?

**Comment by Ninjustin649** [comment]
I also had this issue. I resolved it by setting "public_baseurl: https://matrix.domain.name/" in homeserver.yaml. After restarting the matrix synapse service it started hosting the .well-known file.

**Comment by Aicnal** [comment]
> Solved! I had to add the .well-known information to my reverse proxy.
> 
> Follow [this guide](https://element-hq.github.io/synapse/latest/setup/installation.html#client-well-known-uri) and set up the files manually, then you can sign in via Element.

So, what should I do is just add this one in my reverse proxy instead of change any config of homeserver.yml? I am a little confuse about `.well-known` or other file.

**Comment by goirijo** [comment]
> > Solved! I had to add the .well-known information to my reverse proxy.
> > Follow [this guide](https://element-hq.github.io/synapse/latest/setup/installation.html#client-well-known-uri) and set up the files manually, then you can sign in via Element.
> 
> So, what should I do is just add this one in my reverse proxy instead of change any config of homeserver.yml? I am a little confuse about `.well-known` or other file.

I did not need to follow the nginx configuration to solve this issue on my self hosted synapse. I just went to `etc/matrix-synapse/conf.d` and created a new yaml file:
```
public_baseurl: "https://matrix.domain.com"
```
