### ISSUE TITLE
Push Notifications Not Working After Changing Android Package Name

### ISSUE THREAD

**Issue by nadeemkhan** [element-hq/element-android#8902]
### Steps to reproduce

Changed Android package name from com.oldpackage.app to com.getsafenow.app.
Updated Firebase configuration with a new google-services.json file.
Configured Synapse to use Sygnal as the push gateway:

push:
  gateway: "http://127.0.0.1:5000/_matrix/push/v1/notify"
Restarted Synapse and Sygnal services.
Verified that Sygnal is correctly configured and running on port 5000.

### Outcome

Push notifications are no longer received on the Android app after the package name change.

### Your phone model

OnePlus 10R

### Operating system version

Android 13

### Application version and app store

Element v1.6.12

### Homeserver

https://spydefense.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by msulmanzig** [comment]
hi am facing same issue.
but i think it is due to the change of the **Cloud Messaging API (Legacy)**.
kindly connect me at whatsapp at (+923355219298) so we can try to understand this issue together and resolve it.
and kindly send me your sygnal configurations also.

**Comment by toshanmugaraj** [comment]
You have to setup new FCM configuration with the updated package name
